import React from 'react';
import { motion } from 'motion/react';
import { X, Sparkles, Share2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface DigestModalProps {
  isOpen: boolean;
  onClose: () => void;
  content: string;
}

export function DigestModal({ isOpen, onClose, content }: DigestModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[80] flex items-center justify-center p-4">
      <motion.div 
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.9, opacity: 0, y: 20 }}
        className="bg-white rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]"
      >
        {/* Header */}
        <div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-6 text-white flex justify-between items-start shrink-0">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="bg-white/20 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider backdrop-blur-md">
                Weekly Rewind
              </span>
              <Sparkles size={16} className="text-yellow-300" />
            </div>
            <h2 className="text-3xl font-bold">Your AI Digest</h2>
            <p className="text-indigo-100 opacity-90 mt-1">Curated insights from your saved content.</p>
          </div>
          <button 
            onClick={onClose}
            className="bg-white/10 hover:bg-white/20 p-2 rounded-full transition-colors"
          >
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="p-8 overflow-y-auto custom-scrollbar">
          <div className="prose prose-indigo max-w-none">
            <ReactMarkdown>{content}</ReactMarkdown>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-100 bg-gray-50 flex justify-between items-center shrink-0">
          <p className="text-xs text-gray-500">Generated by Gemini 3 Pro</p>
          <button className="flex items-center gap-2 text-indigo-600 font-medium hover:text-indigo-700 text-sm">
            <Share2 size={16} /> Share Newsletter
          </button>
        </div>
      </motion.div>
    </div>
  );
}
